list(
  study = "05_annotation_models",
  task = "single_trait_annotation_informed_models",
  profile = Sys.getenv("SBLR_BENCH_PROFILE", "development"),
  development_settings = TRUE,
  data_source = "qgg_example",
  example_data = list(
    repository = "psoerensen/qgdata",
    commit = "6cca5819e711d326cfb2614d7e9d9f34942612cd",
    subdirectory = "simulated_human_data",
    files = c("human.bed", "human.bim", "human.fam", "human.pheno", "human.covar"),
    size_bytes = c(human.bed = 62500003, human.bim = 1882359,
      human.fam = 117786, human.pheno = 92786, human.covar = 641513),
    md5 = c(human.bed = "e89bea9a6cedd9eeef3fd0a5c807db81",
      human.bim = "0105119b04c67b7ac7f66cc5e6680963",
      human.fam = "3c5db3d9eb7f3fc893c75f6f2b89836d",
      human.pheno = "6a9e7cb1162e43999c170a363863176d",
      human.covar = "d06002aa2b1b79bdc4c0e92c21f27ae5")
  ),
  chr = 1L,
  sample_limit = NULL,
  trait = "trait1",
  split = list(train_fraction = 0.70, seed = 3101L),
  qc = list(excludeMAF = 0.05, excludeMISS = 0.05, excludeCGAT = TRUE,
    excludeINDEL = TRUE, excludeDUPS = TRUE, excludeHWE = 1e-12,
    excludeMHC = FALSE),
  sparse_ld = list(max_distance_bp = 0, max_distance_variants = 1000L,
    r2_threshold = 0.001, block_size = 1024L, nthreads = 1L),
  scenarios = c("informative_annotations", "uninformative_annotations"),
  methods = c("st_bed_bayesr", "st_bed_bayesrc",
    "st_csr_sbayesr", "st_csr_sbayesrc"),
  method_labels = c(
    st_bed_bayesr = "ST-BED BayesR",
    st_bed_bayesrc = "ST-BED BayesRC",
    st_csr_sbayesr = "ST-CSR SBayesR",
    st_csr_sbayesrc = "ST-CSR SBayesRC"),
  mixture_var = c(0, 0.01, 0.1, 1),
  simulation = list(
    h2 = 0.30, replicate_count = 5L,
    nonnull_sanity_range = c(20L, 100L),
    informative_nonintercept_alpha = matrix(c(
      0.98, 0.20, 0.00,
      0.25, 0.00, 0.20,
      0.00, 0.00, 0.00
    ), nrow = 3L, byrow = TRUE,
    dimnames = list(c("enriched_binary", "continuous_signal", "null_annotation"),
      paste0("step_", 1:3))),
    target_expected_nonnull = 50,
    active_component_weights = c(0.60, 0.30, 0.10)
  ),
  annotation = list(seed = 5201L, enriched_fraction = 0.10),
  seeds = list(
    data_selection = 3101L, annotation = 5201L, scenario_base = 5301L,
    replicate_stride = 100L, component_offset = 11L, effect_offset = 23L,
    residual_offset = 37L, fit_base = 600000L, chain_stride = 101L),
  convergence_pilot = list(
    nit = 3000L, nburn = 0L, nthin = 1L, nchains = 4L, ncores = 4L,
    burnin_candidates = c(250L, 500L, 750L, 1000L),
    retained_candidates = c(500L, 1000L, 1500L, 2000L, 2500L),
    thresholds = list(rhat = 1.01, ess_bulk = 400,
      ess_tail = 400, relative_mcse = 0.05, chain_count = 4L)),
  alpha_prior = list(intercept_flat = TRUE, sigmaSqAlpha_a = 2,
    sigmaSqAlpha_b = 2, sigmaSqAlpha_init = c(1, 1, 1),
    alpha_update_every = 1L, pi_floor = 1e-12),
  baseline_recommendation_source = Sys.getenv("SBLR_BENCH_RECOMMENDATIONS",
    file.path("results", "reference", "04_convergence", "current-selection",
      "method_recommendations.csv")),
  convergence_capsule = Sys.getenv("SBLR_BENCH_STUDY05_CAPSULE",
    file.path("results", "reference", "05_annotation_models", "current-convergence")),
  benchmark_capsule = file.path("results", "reference",
    "05_annotation_models", "st-annotation-models-five-replicate-development-v1"),
  source_audit = c(
    "R/mtblr-bayesrc.R", "R/sbayesrc-helpers.R",
    "R/blr-extended-convergence.R", "R/mtblr-bed.R", "R/mtblr-csr.R",
    "R/stblr-csr-annot.R", "R/stblr-csr-sbayesrc.R",
    "R/sparse_ld_bed_helper.R",
    "tests/testthat/test-stblr-bed-interface.R",
    "tests/testthat/test-stblr-csr-interface.R",
    "tests/testthat/test-blr-extended-parameter-diagnostics.R",
    "tests/testthat/test-blr-extended-probability-diagnostics.R")
)
