# Exact scientific specification for Study 06. The benchmark profile preserves
# the audited two-scenario, five-replicate, four-method design. No performance
# run is permitted until all four annotation qualification entries pass.

spec <- list(
  study = "06_annotation_models",
  task = "annotation_models",
  status = "qualification_pending",
  supported_profiles = list(
    workshop = list(replicate_count = 1L,
      suitable_for_method_performance_claims = FALSE),
    benchmark = list(replicate_count = 5L,
      suitable_for_method_performance_claims = FALSE)),
  data = list(
    source = "qgg_example", chromosome = 1L, sample_limit = 2000L,
    expected_sample_count = 2000L, expected_marker_count = 37991L,
    trait = "trait1",
    alignment = list(samples = "exact IDs in Glist order",
      markers = "exact chromosome-1 QC marker IDs in Glist order",
      annotations = "rownames must equal ordered marker IDs"),
    preprocessing = list(genotypes = "training-only centering and scaling",
      summary_statistics = "training samples only with training allele frequencies"),
    example_data = list(
      repository = "psoerensen/qgdata",
      commit = "6cca5819e711d326cfb2614d7e9d9f34942612cd",
      subdirectory = "simulated_human_data",
      files = c("human.bed", "human.bim", "human.fam", "human.pheno",
        "human.covar"),
      size_bytes = c(human.bed = 62500003, human.bim = 1882359,
        human.fam = 117786, human.pheno = 92786, human.covar = 641513),
      md5 = c(human.bed = "e89bea9a6cedd9eeef3fd0a5c807db81",
        human.bim = "0105119b04c67b7ac7f66cc5e6680963",
        human.fam = "3c5db3d9eb7f3fc893c75f6f2b89836d",
        human.pheno = "6a9e7cb1162e43999c170a363863176d",
        human.covar = "d06002aa2b1b79bdc4c0e92c21f27ae5")),
    sparse_ld = list(max_distance_bp = 0, max_distance_variants = 1000L,
      r2_threshold = 0.001, block_size = 1024L, nthreads = 1L)),
  split = list(train_fraction = 0.70, seed = 3101L,
    expected_train_count = 1400L, expected_test_count = 600L),
  markers = list(qc = list(excludeMAF = 0.05, excludeMISS = 0.05,
    excludeCGAT = TRUE, excludeINDEL = TRUE, excludeDUPS = TRUE,
    excludeHWE = 1e-12, excludeMHC = FALSE)),
  replicate_count = 5L,
  scenarios = list(
    informative_annotations = list(
      effect_distribution = "annotation_variance_mixture",
      annotation_policy = "informative_joint_binary_continuous"),
    uninformative_annotations = list(
      effect_distribution = "annotation_variance_mixture",
      annotation_policy = "marginally_matched_intercept_only")),
  annotation_design = list(
    implementation = file.path("studies", "06_annotation_models",
      "annotation-design.R"),
    columns = c("Intercept", "enriched_binary", "continuous_signal",
      "null_annotation"),
    seed = 5201L, enriched_fraction = 0.10,
    standardization = "sample mean zero and sample SD one",
    missing_values = "forbidden",
    informative_nonintercept_alpha = matrix(c(
      0.98, 0.20, 0.00,
      0.25, 0.00, 0.20,
      0.00, 0.00, 0.00), nrow = 3L, byrow = TRUE,
      dimnames = list(c("enriched_binary", "continuous_signal",
        "null_annotation"), paste0("step_", 1:3)))),
  methods = list(
    st_bed_bayesr = list(label = "ST-BED BayesR",
      interface = "stblr_bed", native_method = "bayesr",
      representation = "BED", prior_class = "BayesR",
      annotation_aware = FALSE,
      computational_policy = "full unscheduled BED sweep"),
    st_bed_bayesrc = list(label = "ST-BED BayesRC",
      interface = "stblr_bed", native_method = "bayesrc",
      representation = "BED", prior_class = "BayesRC",
      annotation_aware = TRUE,
      computational_policy = "full unscheduled BED sweep"),
    st_csr_sbayesr = list(label = "ST-CSR SBayesR",
      interface = "stblr_csr", native_method = "sbayesr",
      representation = "CSR", prior_class = "BayesR",
      annotation_aware = FALSE,
      computational_policy = "training-only sparse LD"),
    st_csr_sbayesrc = list(label = "ST-CSR SBayesRC",
      interface = "stblr_csr_annot", native_method = "sbayesrc",
      annotation_model = "annotation_probit_stick",
      representation = "CSR", prior_class = "BayesRC",
      annotation_aware = TRUE,
      computational_policy = "training-only sparse LD")),
  controls = list(
    simulation = list(h2 = 0.30, target_expected_nonnull = 50,
      nonnull_sanity_range = c(20L, 100L),
      mixture_var = c(0, 0.01, 0.1, 1),
      active_component_weights = c(0.60, 0.30, 0.10)),
    priors = list(h2 = 0.30, bayesr_active_probability = 50 / 37991,
      bayesr_mixture_var = c(0, 0.01, 0.1, 1),
      intercept_flat = TRUE, sigmaSqAlpha_a = 2,
      sigmaSqAlpha_b = 2, sigmaSqAlpha_init = c(1, 1, 1),
      alpha_update_every = 1L, pi_floor = 1e-12,
      updateAlpha = TRUE, updateB = TRUE, updateE = TRUE),
    baseline = list(recommendation_source = file.path("results", "reference",
      "04_convergence", "current-selection", "method_recommendations.csv")),
    workshop = list(nit = 500L, nburn = 250L, nthin = 1L,
      nchains = 1L, ncores = 1L, convergence = "none", keep_chains = TRUE,
      convergence_control = list(warn = FALSE, keep_traces = TRUE))),
  qualification = list(
    entries = data.frame(
      scenario = rep(c("informative_annotations",
        "uninformative_annotations"), each = 2L),
      replicate = 1L,
      method = rep(c("st_bed_bayesrc", "st_csr_sbayesrc"), 2L),
      stringsAsFactors = FALSE),
    maximum_history = 9000L, nburn = 0L, nthin = 1L,
    nchains = 4L, ncores = 4L,
    burnin_candidates = c(1000L, 2000L, 3000L),
    retained_candidates = c(2000L, 4000L, 6000L),
    thresholds = list(rhat = 1.01, ess_bulk = 400,
      ess_tail = 400, relative_mcse = 0.05, chain_count = 4L),
    failure_rule = "stop final benchmark when any required quantity lacks a passing candidate window",
    decision_path = file.path("qualification", "qualification_decision.json")),
  seeds = list(data_selection = 3101L, annotation = 5201L,
    scenario_base = 5301L, scenario_stride = 100000L,
    replicate_stride = 100L, component_offset = 11L, effect_offset = 23L,
    residual_offset = 37L, fit_base = 600000L, method_stride = 10L,
    chain_stride = 101L),
  estimands = data.frame(
    estimand_id = c("annotation_alpha", "marker_prior_component_probability",
      "marker_nonnull_probability", "marker_effect", "genetic_value",
      "genetic_variance", "residual_variance", "heritability"),
    definition = c("retained draw of each annotation-by-stick coefficient",
      "draw-wise sblr probit-stick component probability averaged over retained draws",
      "one minus posterior null-component probability", "posterior mean effect",
      "scaled genotype times posterior mean effects", "posterior vgs",
      "posterior ves", "vgs/(vgs+ves)"),
    required = TRUE, stringsAsFactors = FALSE),
  metrics = c("alpha_bias", "alpha_rmse", "alpha_coverage_95",
    "alpha_interval_width_95", "prior_component_probability_rmse",
    "prior_component_probability_correlation", "prior_expected_active_error",
    "posterior_mean_prior_enriched",
    "posterior_mean_prior_unannotated", "enriched_prior_contrast",
    "causal_marker_pip", "causal_marker_rank",
    "top_k_recovery", "precision", "recall", "pip_auprc", "pip_auroc",
    "pip_brier", "effect_rmse", "effect_correlation",
    "genetic_value_correlation", "heritability_recovery",
    "genetic_variance_recovery", "residual_variance_recovery", "runtime",
    "convergence", "paired_annotation_advantage", "scenario_interaction"),
  validation = list(oracle_tolerance = 1e-10,
    expected_sample_count = 2000L, expected_marker_count = 37991L,
    expected_train_count = 1400L, expected_test_count = 600L,
    expected_qualification_count = 4L, expected_fit_count = 40L,
    expected_chain_count = 160L,
    required_annotation_columns = c("Intercept", "enriched_binary",
      "continuous_signal", "null_annotation")),
  frozen_capsule = list(status = "partial_evidence_only",
    current_stop = file.path("results", "reference", "06_annotation_models",
      "current-stop"), final = NULL),
  packages = list(
    sblr = list(version = "0.2.0",
      sha = "02e8c74baa906e83c4a08d42a9cc6339b4e81072"),
    qgg = list(version = "1.1.6"),
    sblrbench = list(version = "0.0.0.9000"),
    qgdata = list(sha = "6cca5819e711d326cfb2614d7e9d9f34942612cd")))
