# Study 06 v2 scientific specification. The tracked v1 current-stop capsule is
# immutable failed development evidence. Qualification and final execution are
# separate opt-in actions and always use the versioned v2 output namespace.

spec <- list(
  study = "06_annotation_models",
  task = "annotation_models",
  study_version = "v2_identifiable_qualification",
  status = "designed_qualification_not_run",
  versioning = list(
    current_profile = "v2_identifiable_qualification",
    profiles = list(
      v1_sparse_qualification_failed = list(
        status = "failed_development_evidence_preserved",
        source = "Git history through 964bf188fc990d5fbbad0ea00592b288c4442723",
        evidence = file.path("results", "reference", "06_annotation_models",
          "current-stop"), completed_benchmark = FALSE),
      v1_sparse_stress = list(
        status = "preserved_not_run",
        purpose = paste("Sparse late-stick stress: prediction, PIP, active-count,",
          "variance, and numerical-integrity assessment; not precise late-stick",
          "annotation recovery qualification."),
        marker_count = 37991L, training_count = 1400L,
        target_expected_nonnull = 50L,
        active_component_weights = c(.60, .30, .10),
        scenarios = c("informative_annotations", "uninformative_annotations")),
      v2_identifiable_qualification = list(
        status = "designed_scaffolded_not_run",
        purpose = "Primary identifiable BayesRC/SBayesRC qualification")),
    output_namespace = "v2_identifiable_qualification"),
  supported_profiles = list(
    workshop = list(replicate_count = 1L,
      suitable_for_method_performance_claims = FALSE),
    benchmark = list(replicate_count = 5L,
      suitable_for_method_performance_claims = FALSE)),
  data = list(
    source = "qgg_example", chromosome = 1L, sample_limit = 2000L,
    expected_sample_count = 2000L, expected_qc_marker_count = 37991L,
    expected_marker_count = 1500L, trait = "trait1",
    alignment = list(samples = "exact IDs in Glist order",
      markers = "deterministic separated-window order",
      annotations = "rownames must equal ordered marker IDs",
      method_inputs = "BED and retained block eigen use identical marker order"),
    preprocessing = list(genotypes = "training-only centering and scaling",
      summary_statistics = "training samples only with training allele frequencies"),
    block_design = list(marker_target = 1500L, block_count = 15L,
      block_size = 100L, selection = "centered consecutive QC markers within 15 equal ordered genomic strata",
      representation = "low_rank", eigen_policy = "cumulative_positive_mass",
      eigen_prop = 0.995, cross_block_audit = "complete training correlation"),
    example_data = list(
      repository = "psoerensen/qgdata",
      commit = "6cca5819e711d326cfb2614d7e9d9f34942612cd",
      subdirectory = "simulated_human_data",
      files = c("human.bed", "human.bim", "human.fam", "human.pheno",
        "human.covar"),
      size_bytes = c(human.bed = 62500003, human.bim = 1882359,
        human.fam = 117786, human.pheno = 92786, human.covar = 641513),
      md5 = c(human.bed = "e89bea9a6cedd9eeef3fd0a5c807db81",
        human.bim = "0105119b04c67b7ac7f66cc5e6680963",
        human.fam = "3c5db3d9eb7f3fc893c75f6f2b89836d",
        human.pheno = "6a9e7cb1162e43999c170a363863176d",
        human.covar = "d06002aa2b1b79bdc4c0e92c21f27ae5"))),
  split = list(train_fraction = 0.70, seed = 3101L,
    expected_train_count = 1400L, expected_test_count = 600L),
  markers = list(qc = list(excludeMAF = 0.05, excludeMISS = 0.05,
    excludeCGAT = TRUE, excludeINDEL = TRUE, excludeDUPS = TRUE,
    excludeHWE = 1e-12, excludeMHC = FALSE)),
  replicate_count = 5L,
  scenarios = list(
    informative_annotations = list(
      effect_distribution = "annotation_variance_mixture",
      annotation_policy = "moderate_nonoracle_binary_continuous"),
    uninformative_annotations = list(
      effect_distribution = "annotation_variance_mixture",
      annotation_policy = "marginally_matched_intercept_only")),
  annotation_design = list(
    implementation = file.path("studies", "06_annotation_models",
      "annotation-design.R"),
    columns = c("Intercept", "enriched_binary", "continuous_signal",
      "null_annotation"),
    seed = 5201L, enriched_fraction = 0.15,
    enriched_expected_nonnull_share_range = c(.50, .60),
    standardization = "sample mean zero and sample SD one",
    missing_values = "forbidden",
    informative_nonintercept_alpha = matrix(c(
      1.60, .30, .20,
       .30, .15, .10,
       .00, .00, .00), nrow = 3L, byrow = TRUE,
      dimnames = list(c("enriched_binary", "continuous_signal",
        "null_annotation"), paste0("step_", 1:3)))),
  methods = list(
    st_bed_bayesr = list(label = "ST-BED BayesR",
      interface = "stblr_bed", native_method = "bayesr",
      representation = "BED", prior_class = "BayesR",
      annotation_aware = FALSE,
      computational_policy = "full unscheduled BED sweep"),
    st_bed_bayesrc = list(label = "ST-BED BayesRC",
      interface = "stblr_bed", native_method = "bayesrc",
      representation = "BED", prior_class = "BayesRC",
      annotation_aware = TRUE,
      computational_policy = "full unscheduled BED sweep"),
    st_block_eigen_sbayesr = list(label = "ST block-eigen SBayesR",
      interface = "stblr_block_eigen", native_method = "sbayesr",
      representation = "block_eigen_low_rank", prior_class = "BayesR",
      annotation_aware = FALSE, operator_representation = "low_rank",
      eigen_policy = "cumulative_positive_mass", eigen_prop = 0.995,
      computational_policy = "prespecified retained block factorization"),
    st_block_eigen_sbayesrc = list(label = "ST block-eigen SBayesRC",
      interface = "stblr_block_eigen", native_method = "sbayesrc",
      annotation_model = "annotation_probit_stick",
      representation = "block_eigen_low_rank", prior_class = "BayesRC",
      annotation_aware = TRUE, operator_representation = "low_rank",
      eigen_policy = "cumulative_positive_mass", eigen_prop = 0.995,
      computational_policy = "prespecified retained block factorization")),
  controls = list(
    simulation = list(h2 = 0.50, target_expected_nonnull = 180L,
      nonnull_sanity_range = c(160L, 200L),
      mixture_var = c(0, 0.01, 0.1, 1),
      active_component_weights = c(.50, .30, .20),
      minimum_realized_active_counts = c(60L, 30L, 20L),
      minimum_stick_eligible = c(500L, 120L, 50L),
      minimum_stick_binary_outcome = c(100L, 25L, 20L),
      realized_h2_tolerance = .02),
    priors = list(h2 = 0.50, bayesr_active_probability = 180 / 1500,
      bayesr_mixture_var = c(0, 0.01, 0.1, 1),
      annotation_intercept_prior = "proper_default", intercept_flat = NULL,
      sigmaSqAlpha_a = 2, sigmaSqAlpha_b = 2,
      sigmaSqAlpha_init = c(1, 1, 1), alpha_update_every = 1L,
      pi_floor = 1e-12, updateAlpha = TRUE, updateB = TRUE, updateE = TRUE),
    baseline = list(recommendation_source = file.path("results", "reference",
      "04_convergence", "current-selection", "method_recommendations.csv")),
    workshop = list(nit = 20L, nburn = 10L, nthin = 1L,
      nchains = 1L, ncores = 1L, convergence = "none", keep_chains = TRUE,
      convergence_control = list(warn = FALSE, keep_traces = TRUE))),
  diagnostic_profiles = list(
    standard = list(enabled = TRUE, public_api_supported = TRUE),
    fixed_true_annotation_coefficients = list(enabled = FALSE,
      public_api_supported = TRUE,
      controls = list(updateAlpha = FALSE, initialize_at_truth = TRUE),
      purpose = "isolate annotation-update feedback"),
    fixed_true_marker_component_probabilities = list(enabled = FALSE,
      public_api_supported = FALSE,
      reason = "No current public BED/block-eigen API accepts fixed marker-specific component probabilities.")),
  qualification = list(
    entries = data.frame(
      scenario = rep(c("informative_annotations", "uninformative_annotations"),
        each = 2L), replicate = 1L,
      method = rep(c("st_bed_bayesrc", "st_block_eigen_sbayesrc"), 2L),
      stringsAsFactors = FALSE),
    maximum_history = 9000L, nburn = 0L, nthin = 1L,
    nchains = 4L, ncores = 4L,
    burnin_candidates = c(1000L, 2000L, 3000L),
    retained_candidates = c(2000L, 4000L, 6000L),
    thresholds = list(rhat = 1.01, ess_bulk = 400,
      ess_tail = 400, relative_mcse = 0.05, chain_count = 4L),
    gating_focus = c("st_bed_bayesrc", "st_block_eigen_sbayesrc"),
    scientific_tolerances = list(
      directional_posterior_probability = .90,
      compatibility_interval = .95,
      maximum_material_ranking_decrease = .02,
      maximum_material_prediction_correlation_decrease = .02,
      maximum_bed_block_prediction_difference = .05,
      maximum_bed_block_h2_difference = .05,
      minimum_bed_block_effect_correlation = .95),
    expectations = list(
      informative = c("annotation directions and intervals",
        "no material ranking or prediction worsening",
        "scientifically consistent BED/block-eigen variance and prediction"),
      uninformative = c("non-intercept effects compatible with zero",
        "no persistent prior contrast", "no systematic annotation advantage")),
    failure_rule = "stop final benchmark when any required quantity lacks a passing candidate window",
    decision_path = file.path("qualification", "qualification_decision.json")),
  seeds = list(data_selection = 3101L, annotation = 5201L,
    scenario_base = 5301L, scenario_stride = 100000L,
    replicate_stride = 100L, component_offset = 11L, effect_offset = 23L,
    residual_offset = 37L, fit_base = 600000L, method_stride = 10L,
    chain_stride = 101L),
  estimands = data.frame(
    estimand_id = c("annotation_alpha", "annotation_variance",
      "stick_counts", "marker_prior_component_probability",
      "expected_nonnull", "marker_nonnull_probability", "marker_effect",
      "genetic_value", "validation_prediction", "genetic_variance",
      "residual_variance", "heritability", "base_effect_variance",
      "component_occupancy"),
    definition = c("retained annotation-by-stick coefficient draws",
      "retained annotation variance draws", "eligible and binary outcomes",
      "draw-wise marker component prior", "draw-wise expected active count",
      "one minus posterior null probability", "posterior mean effect",
      "scaled genotype times posterior mean effects", "held-out phenotype prediction",
      "posterior vgs", "posterior ves", "vgs/(vgs+ves)", "posterior vbs",
      "realized chain allocation counts"),
    required = TRUE, stringsAsFactors = FALSE),
  metrics = c("annotation_direction", "alpha_coverage_95",
    "null_annotation_compatibility", "prior_component_probability_rmse",
    "prior_expected_active_error", "enriched_prior_contrast",
    "continuous_prior_contrast", "causal_marker_rank", "pip_auprc",
    "pip_auroc", "effect_rmse", "effect_correlation",
    "genetic_value_correlation", "prediction_correlation",
    "heritability_recovery", "genetic_variance_recovery",
    "residual_variance_recovery", "component_occupancy", "runtime",
    "convergence", "paired_annotation_advantage", "scenario_interaction"),
  validation = list(oracle_tolerance = 1e-10,
    expected_sample_count = 2000L, expected_qc_marker_count = 37991L,
    expected_marker_count = 1500L, expected_train_count = 1400L,
    expected_test_count = 600L, expected_qualification_count = 4L,
    expected_fit_count = 40L, expected_chain_count = 160L,
    required_annotation_columns = c("Intercept", "enriched_binary",
      "continuous_signal", "null_annotation")),
  frozen_capsule = list(status = "failed_development_evidence_preserved",
    current_stop = file.path("results", "reference", "06_annotation_models",
      "current-stop"), final = NULL),
  output = list(required_path_component = "v2_identifiable_qualification"),
  packages = list(
    sblr = list(version = "0.2.0",
      sha = "f2e3647920ed7e8b1ea9d47a6571b3753285682a"),
    qgg = list(version = "1.1.6"),
    sblrbench = list(version = "0.0.0.9000"),
    qgdata = list(sha = "6cca5819e711d326cfb2614d7e9d9f34942612cd")))
