.study06_root <- if (file.exists(file.path("studies", "03_parameter_estimation",
  "spec.R"))) "." else file.path("..", "..")
.study06_parameter_spec <- source(file.path(.study06_root, "studies",
  "03_parameter_estimation", "spec.R"), local = TRUE)$value

list(
  study = "06_ld_operator",
  task = "single_trait_ld_operator_benchmark",
  profile = Sys.getenv("SBLR_BENCH_PROFILE", "development"),
  development_settings = TRUE,
  title = "Study 06: Single-trait LD operator benchmark",
  design_revision = "operator_agreement_v2",
  chr = 1L,
  trait = "trait1",
  sample_limit = NULL,
  example_data = .study06_parameter_spec$data$example_data,
  qc = .study06_parameter_spec$markers$qc,
  sparse_ld = .study06_parameter_spec$data$sparse_ld,
  split = list(train_fraction = 0.70, seed = 3101L),
  architectures = c("sparse_homogeneous", "sparse_mixture"),
  architecture_specs = .study06_parameter_spec$scenarios,
  replicate_count = 5L,
  simulation = list(h2 = 0.30, n_causal = 50L),
  configurations = c("bed", "full_csr", "block_csr",
    "block_eigen_unfiltered", "block_eigen_hard",
    "block_eigen_ridge_fixed"),
  configuration_labels = c(
    bed = "Individual-level BED",
    full_csr = "Full sparse-LD CSR",
    block_csr = "Runtime-matched block CSR",
    block_eigen_unfiltered = "Unfiltered block eigen",
    block_eigen_hard = "Hard-filtered block eigen",
    block_eigen_ridge_fixed = "Fixed-ridge block eigen"),
  block_candidates = c(250L, 500L, 1000L),
  selected_block_size = 1000L,
  hard_tau_candidates = c(0.02, 0.05, 0.10),
  selected_hard_tau = 0.10,
  unfiltered = list(eigen_filter = "ridge_fixed", eigen_eta = 0),
  ridge_fixed_shrinkage_candidates = c(0.001, 0.01, 0.05),
  selected_ridge_shrinkage = 0.01,
  selected_ridge_eta = 0.01 / 0.99,
  ridge_lw = list(eigen_filter = "ridge_lw", eigen_tau = 0,
    eigen_eta = 0),
  operator_tolerance = list(absolute = 2e-3, relative = 2e-6,
    product_absolute = 2e-2, quadratic_absolute = 5e-2,
    probability = 1e-10),
  operator_probe_count = 5L,
  pilot_gate = list(maximum_heritability_difference = 0.15,
    maximum_prediction_correlation_difference = 0.10,
    minimum_posterior_effect_correlation = 0.95),
  recommendation_source = file.path("results", "reference",
    "04_convergence", "current-selection",
    "method_recommendations.csv"),
  convergence = list(
    maximum_nit = 3000L, maximum_nburn = 0L, nthin = 1L,
    nchains = 4L, ncores = 4L,
    burnin_candidates = c(250L, 500L, 1000L),
    retained_candidates = c(250L, 500L, 1000L, 2000L),
    thresholds = list(rhat = 1.01, ess_bulk = 400,
      ess_tail = 400, relative_mcse = 0.05, chain_count = 4L)),
  seeds = list(
    data_selection = 3101L, simulation_base = 61000L,
    architecture_stride = 10000L, replicate_stride = 100L,
    effect_offset = 11L, residual_offset = 37L,
    fit_base = 600000L, configuration_stride = 1000L,
    chain_stride = 101L, operator_probe = 6601L),
  local_dir = file.path("results", "local", "study06_ld_operator"),
  convergence_capsule = file.path("results", "reference",
    "06_ld_operator", "current"),
  benchmark_capsule = file.path("results", "reference",
    "06_ld_operator", "current"),
  source_audit = c(
    "R/stblr-public.R", "R/stblr-block-eigen.R",
    "R/stblr-csr-annot.R", "R/mtblr-bed.R", "R/mtblr-csr.R",
    "R/mtblr-block-eigen.R", "R/mtblr-bayesr.R",
    "R/mtblr-bayesrc.R", "R/interface_mtblr.R",
    "R/sparse_ld_bed_helper.R", "src/st_bed_decode.h",
    "src/st_block_eigen.cpp", "src/blr_block_eigen.h",
    "tests/testthat/helper-blr-fixtures.R",
    "tests/testthat/test-stblr-block-eigen.R",
    "tests/testthat/test-blr-operator-reductions.R",
    "docs/methods/block_eigen_operator.qmd",
    "docs/dev/blr_output_schema.md",
    "docs/dev/blr_model_capability_matrix.md",
    "docs/methods/mt_bayesr_sbayesr.qmd",
    "docs/methods/mt_bayesrc_sbayesrc.qmd",
    "examples/workflows/operator_comparison_workflow.R")
)
