.study08_root <- if (file.exists(file.path("studies", "05_ld_operator",
  "spec.R"))) "." else file.path("..", "..")
.study08_study05 <- source(file.path(.study08_root, "studies",
  "05_ld_operator", "spec.R"), local = TRUE)$value

list(
  study = "08_mt_validation",
  task = "multivariate_implementation_validation",
  title = "Study 08: Multivariate implementation validation",
  development_settings = TRUE,
  execution_status = "paused_pending_retained_low_rank_mt_operator",
  pause_reason = paste(
    "Study 08 MT block-eigen execution is paused because the current",
    "mtblr_block_eigen() backend reconstructs and stores dense packed blocks.",
    "Primary execution resumes only after the retained low-rank MT operator",
    "has been implemented and validated in sblr."),
  trait_names = c("trait1", "trait2"),
  trait_count = 2L,
  chr = 1L,
  sample_count = 5000L,
  split = list(train_fraction = 0.70, seed = 3701L),
  example_data = .study08_study05$data$example_data,
  qc = .study08_study05$markers$qc,
  sparse_ld = .study08_study05$data$sparse_ld,
  marker_candidates = c(1000L, 2000L, 4000L, 8000L),
  minimum_marker_count = 2000L,
  block_size = 1000L,
  models = rbind(
    neither = c(0L, 0L),
    trait1_only = c(1L, 0L),
    trait2_only = c(0L, 1L),
    both = c(1L, 1L)),
  model_probabilities = c(neither = 0.99,
    trait1_only = 0.003, trait2_only = 0.003, both = 0.004),
  contract_architectures = c("independent", "fully_shared_positive",
    "partially_shared", "fully_shared_negative"),
  main_architectures = c("independent", "partially_shared"),
  replicate_count = 5L,
  simulation = list(
    h2 = c(trait1 = 0.30, trait2 = 0.30),
    state_counts = list(
      independent = c(trait1_only = 25L, trait2_only = 25L, both = 0L),
      fully_shared_positive = c(trait1_only = 0L, trait2_only = 0L, both = 50L),
      partially_shared = c(trait1_only = 15L, trait2_only = 15L, both = 20L),
      fully_shared_negative = c(trait1_only = 0L, trait2_only = 0L, both = 50L))),
  implementations = c("mt_bed_bayesc", "mt_csr_sbayesc",
    "mt_block_eigen_sbayesc"),
  contract_implementations = c("mt_bed_bayesc", "mt_csr_sbayesc",
    "mt_block_csr_sbayesc"),
  operator_validation_implementations = c("mt_csr_sbayesc",
    "mt_block_csr_sbayesc", "mt_block_eigen_sbayesc"),
  runtime_implementations = c("mt_bed_bayesc", "mt_csr_sbayesc",
    "mt_block_csr_sbayesc", "mt_block_eigen_sbayesc"),
  unfiltered = list(eigen_filter = "ridge_fixed", eigen_eta = 0),
  operator_tolerance = .study08_study05$operators$equivalence_tolerances,
  operator_probe_count = .study08_study05$validation$operator_probe_count,
  runtime_limits = list(
    maximum_projected_four_chain_seconds = 2 * 60 * 60,
    maximum_projected_benchmark_seconds = 36 * 60 * 60,
    maximum_memory_fraction = 0.70,
    conservative_memory_limit_bytes = 16 * 1024^3,
    maximum_fit_object_bytes = 5 * 1024^3),
  timing = list(nit = 30L, nburn = 10L, nthin = 1L,
    nchains = 1L, ncores = 1L, four_chain_marker_count = 1000L),
  tiny = list(marker_count = 1000L, sample_count = 750L,
    nit = 12L, nburn = 4L, nchains = 4L, ncores = 4L),
  convergence = list(
    maximum_nit = 3000L, maximum_nburn = 0L, nthin = 1L,
    nchains = 4L, ncores = 4L,
    burnin_candidates = c(250L, 500L, 1000L),
    retained_candidates = c(250L, 500L, 1000L, 2000L),
    thresholds = list(rhat = 1.01, ess_bulk = 400,
      ess_tail = 400, relative_mcse = 0.05, chain_count = 4L)),
  seeds = list(
    sample_selection = 3701L, marker_selection = 3703L,
    simulation_base = 70000L, architecture_stride = 10000L,
    replicate_stride = 100L, state_offset = 11L,
    effect_offset = 23L, residual_offset = 47L,
    fit_base = 700000L, implementation_stride = 1000L,
    chain_stride = 101L, permutation = 7701L,
    operator_probe = 7703L),
  local_dir = file.path("results", "local", "study08_mt_validation"),
  contract_capsule = file.path("results", "reference",
    "08_mt_validation", "mtblr-contract-runtime-development-v1"),
  convergence_capsule = file.path("results", "reference",
    "08_mt_validation", "mtblr-convergence-development-v1"),
  benchmark_capsule = file.path("results", "reference",
    "08_mt_validation", "mtblr-five-replicate-development-v1"),
  consulted_sblr_sources = c(
    "R/mtblr-bed.R", "R/mtblr-csr.R", "R/mtblr-block-eigen.R",
    "R/mtblr-summary-chains.R", "R/blr-extended-convergence.R",
    "R/blr-unified.R", "R/mtblr-bayesr.R", "R/mtblr-bayesrc.R",
    "R/interface_mtblr.R", "tests/testthat/test-blr-unified-convergence.R",
    "tests/testthat/test-blr-unified-public-contract.R",
    "tests/testthat/test-blr-operator-reductions.R",
    "tests/testthat/fixtures/mt-bayesc-reference.R")
)
